### ISSUE TITLE
What is Total Difference?

### ISSUE THREAD

**Issue by 2raj2raj** [GabrielNotman/PT_Logger#1]
Thank you for sharing this. I have successfully set this up on Windows and working very well. But I can't work out what the "Total Difference" field is? Can you please explain?

**Comment by GabrielNotman** [comment]
The _Total Difference_ value is the measure of the difference between the total cost of the open positions and the total current value of those positions.

The _Total Difference_ is the sum of the _Pair_ and _DCA_ differences, where the _Pair Difference_ is the _Pair Current Value_ - _Pair Total Cost_ and similarly, the _DCA Difference_ is the _DCA Current Value_ - _DCA Total Cost_.

**Comment by 2raj2raj** [comment]
Thanks!
